apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: avatar-generator

resources:
- namespace.yaml
- configmap.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- hpa.yaml

commonLabels:
  app: avatar-generator
  version: v1.0.0 