apiVersion: v1
kind: Service
metadata:
  name: avatar-pycor-service
  namespace: brcai
  labels:
    app: avatar-pycor
spec:
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: avatar-pycor 